version: '3.8'
services:
  api:
    build: ./app
    volumes:
      - ./app:/code
    environment:
      FLASK_APP: ./backend/server.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
      MONGO_HOST: $MONGO_HOST
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DATABASE: example_dev
    ports:
      - 5000:5000
    command: bash -c "pip3 install . && flask run"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
  mongo-express:
    image: mongo-express
    restart: always
    environment:  
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
    ports:
      - 4000:8081
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/frontend:/code
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true
    ports:
      - 3000:3000
    command: bash -c "npm install && npm start"
