apiVersion: v1
kind: Service
metadata:
  name: template-flask-react
  labels:
    app: template-flask-react
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  # Replace with the IP of your minikube node / master node
  externalIPs:
    - 192.168.64.2
    - 172.17.0.4
  selector:
    app: template-flask-react
    tier: backend
